//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateApiTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int ID { get; set; }
        public string Job_Description { get; set; }
        public int Working_Hours { get; set; }
        public string Name { get; set; }

       public employee()
        {
             Job_Description="";
            Working_Hours = 0;
            Name = "";
        }

    }
}
